"""the v0.1.0 schema

Revision ID: 0001
Revises:
Create Date: 2026-09-06 13:57:04.236397
"""

from __future__ import annotations

from collections.abc import Sequence

# Autogenerate writes column types out fully qualified but does not import them, so the two this
# project defines are imported here whether or not this particular revision needs them. F401 is
# switched off for this directory in pyproject.toml for exactly that reason.
import hera_storage.base
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_chats",
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", name="entitystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("revoked_at", hera_storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_message_at", hera_storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("pinned_skills", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_chats")),
    )
    with op.batch_alter_table("chat_chats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_chats_created_at"), ["created_at", "id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_chats_last_message_at"), ["last_message_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chat_chats_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_chats_pinned"), ["pinned"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_chats_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_chats_status"), ["status"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("events", sa.JSON(), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("prompt_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_messages_chat_id"), ["chat_id", "sequence"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_messages_created_at"), ["created_at", "id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chat_messages_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "chat_projects",
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", name="entitystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("revoked_at", hera_storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pinned_skills", sa.JSON(), nullable=True),
        sa.Column("default_profile_id", sa.Uuid(), nullable=True),
        sa.Column("default_agent_id", sa.Uuid(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_projects")),
        sa.UniqueConstraint("owner_id", "slug", name=op.f("uq_chat_projects_owner_id")),
    )
    with op.batch_alter_table("chat_projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_projects_archived"), ["archived"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_chat_projects_created_at"), ["created_at", "id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_chat_projects_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_chat_projects_status"), ["status"], unique=False)

    op.create_table(
        "profile_profiles",
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", name="entitystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("revoked_at", hera_storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("disabled_regions", sa.JSON(), nullable=True),
        sa.Column("overrides", sa.JSON(), nullable=True),
        sa.Column("traits", sa.JSON(), nullable=True),
        sa.Column("pinned_skills", sa.JSON(), nullable=True),
        sa.Column("renderer_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_profiles")),
        sa.UniqueConstraint("owner_id", "slug", name=op.f("uq_profile_profiles_owner_id")),
    )
    with op.batch_alter_table("profile_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_profile_profiles_created_at"), ["created_at", "id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_profile_profiles_is_default"), ["is_default"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_profile_profiles_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_profile_profiles_status"), ["status"], unique=False)

    op.create_table(
        "skill_usages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", hera_storage.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("last_used_at", hera_storage.base.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_usages")),
        sa.UniqueConstraint("owner_id", "skill_id", name=op.f("uq_skill_usages_owner_id")),
    )
    with op.batch_alter_table("skill_usages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_usages_created_at"), ["created_at", "id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_skill_usages_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_skill_usages_skill_id"), ["skill_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skill_usages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_usages_skill_id"))
        batch_op.drop_index(batch_op.f("ix_skill_usages_owner_id"))
        batch_op.drop_index(batch_op.f("ix_skill_usages_created_at"))

    op.drop_table("skill_usages")
    with op.batch_alter_table("profile_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_profiles_status"))
        batch_op.drop_index(batch_op.f("ix_profile_profiles_owner_id"))
        batch_op.drop_index(batch_op.f("ix_profile_profiles_is_default"))
        batch_op.drop_index(batch_op.f("ix_profile_profiles_created_at"))

    op.drop_table("profile_profiles")
    with op.batch_alter_table("chat_projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_projects_status"))
        batch_op.drop_index(batch_op.f("ix_chat_projects_owner_id"))
        batch_op.drop_index(batch_op.f("ix_chat_projects_created_at"))
        batch_op.drop_index(batch_op.f("ix_chat_projects_archived"))

    op.drop_table("chat_projects")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_owner_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_chat_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("chat_chats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_chats_status"))
        batch_op.drop_index(batch_op.f("ix_chat_chats_project_id"))
        batch_op.drop_index(batch_op.f("ix_chat_chats_pinned"))
        batch_op.drop_index(batch_op.f("ix_chat_chats_owner_id"))
        batch_op.drop_index(batch_op.f("ix_chat_chats_last_message_at"))
        batch_op.drop_index(batch_op.f("ix_chat_chats_created_at"))

    op.drop_table("chat_chats")
    # ### end Alembic commands ###
